### ISSUE TITLE
WPML duplicate posts with reviews don't save review data

### ISSUE THREAD

**Issue by Stiofan** [GeoDirectory/geodirectory#309]
If transaltion management "Synchronize comments on duplicate content" is set and you have duplicate posts the comment is synced but the review is not.
see:
http://drinking.directory/places/belfast/attractions/test-comments/#comment-34
http://drinking.directory/fr/places-fr/belfast/le-attractions/test-comments/#reviews

**Comment by kprajapatii** [comment]
Fixed
