### ISSUE TITLE
WPML duplicate posts can be edited from frontend

### ISSUE THREAD

**Issue by Stiofan** [GeoDirectory/geodirectory#310]
A duplicate post should not be allowed to be edited from the frontend, this should only allow the original to be edited not any of the duplicates. (maybe redirect) also the changes should be copied over to the duplicates as the backend does.

**Comment by Guust-Flater** [comment]
Do you mean a translated listing? 
How can a user then edit his/her listings in different languages?
It will become the sole job of the admin then to do translations?

**Comment by Stiofan** [comment]
No, not a translation, this is the duplicate feature of WPML.

**Comment by Guust-Flater** [comment]
Pfff, good to know :) 
Thanks, Stiofan.

**Comment by Stiofan** [comment]
we tell people not to use it as it can't really translate custom fields with it, but people like to use it to show the main language of a post in all languages (yeah some people want that)

**Comment by Stiofan** [comment]
@kprajapatii was this fixed with the last pull or is it still open?

**Comment by kprajapatii** [comment]
No this is not fixed yet.

**Comment by kprajapatii** [comment]
#316
