### ISSUE TITLE
"Place" and "Places" in latest core PO file is not translating anymore

### ISSUE THREAD

**Issue by Guust-Flater** [GeoDirectory/geodirectory#317]
"Place" and "Places" in latest core PO file [1.6.15] is not translating anymore on frontend in ADD LISTING form.

See also https://wpgeodirectory.com/support/topic/cant-find-listing-title-listing-description-in-the-po-file/#post-346596
![1](https://cloud.githubusercontent.com/assets/9587794/22167782/582727fa-dfb4-11e6-9899-8d2ef2b7420f.jpg)

**Comment by kprajapatii** [comment]
#316 "Place" and "Places" in latest core PO file is not translating anymore - FIXED
