### ISSUE TITLE
Overlapping map markers

### ISSUE THREAD

**Issue by pol76** [GeoDirectory/geodirectory#340]
This is something that pops up recursively: https://wpgeodirectory.com/support/topic/new-listings-override-old-listing-markers/

Can we think about a solution for a future release?

Thanks

**Comment by Stiofan** [comment]
This might be a solution, i have not checked how memory intensive it might be though, https://github.com/jawj/OverlappingMarkerSpiderfier-Leaflet

**Comment by Stiofan** [comment]
Another user with same request : https://wpgeodirectory.com/support/topic/2-places-1-address/

**Comment by Stiofan** [comment]
@kprajapatii let me know when u start this so we don't both work on it.

**Comment by kprajapatii** [comment]
Fixed https://github.com/GeoDirectory/geodirectory/pull/390/commits/ed2bc50969fd01e6cc0d2248f7b6c2fcc8fa34f0
Check here: https://ppldb.com/kiran/ (markers around glasgow region)
