### ISSUE TITLE
Add shortcode for user favs.

### ISSUE THREAD

**Issue by Stiofan** [GeoDirectory/geodirectory#350]
As titled

**Comment by kprajapatii** [comment]
Fixed
In existing shortcode [gd_listings] two new parameters "show_favorites_only" & "favorites_by_user" added to filter user favorite listings.

"show_favorites_only": If enabled via value then the results will lists only listings favorites by user.
"favorites_by_user"  : Values should be 'current' OR INTEGER user id or empty

If "show_favorites_only" is enabled then 
- For favorites_by_user="current", shortcode will show the listings which are favorites by author of current viewing post.
- For favorites_by_user="12", shortcode will show the listings which are favorites by user id "12".
- For favorites_by_user="" or empty, shortcode will show the listings which are favorites by current logged user(if logged in).

See example of usage https://ppldb.com/kiran/shortcodes/gd-listings-favorites/

**Comment by Stiofan** [comment]
@
