### ISSUE TITLE
Make sure no Fatal Errors if we can prevent them

### ISSUE THREAD

**Issue by pol76** [GeoDirectory/geodirectory#352]
Hi Guys,

we just got a 1 star review, probably because the guy didn't have mbstring or another PHP module installed. Maybe he was an old PHP version.

https://wordpress.org/support/topic/plugin-causes-conflicts/

Whatever it was, I still think we could have prevented this. If GD can't work without mbstring or other PHP module, that we know once in a while are not installed by default, we should check if they are installed before activating the plugin. 

If they are not, we should alert the user to install them before trying to activate the plugin again.

mbstring is definitely the most frequent,  this is another error I saw more than once: https://wpgeodirectory.com/support/topic/event-date-registration-error/#post-360988

On the same subject, the Stripe integration throws a fatal error if installed when the Payment Manager is not installed. We should fix that too.

Thanks

**Comment by mistergiri** [comment]
@Stiofan 

I think we need backward compatibility functions for other mb related functions as well.

Like geodir_strtolower and geodir_strtoupper

https://github.com/GeoDirectory/geodirectory/blob/master/geodirectory-functions/helper_functions.php#L261

Just noticed we are using the following mb related functions without any backward compatibility support.

1. mb_strlen
2. mb_substr
3. mb_strrpos
4. mb_strwidth
5. mb_internal_encoding

**Comment by kprajapatii** [comment]
All multibyte functions used within GD + GD Addons + Themes are replaced by our own functions.
