### ISSUE TITLE
Sort by SC and Widget options

### ISSUE THREAD

**Issue by Stiofan** [GeoDirectory/geodirectory#376]
Make gd_listings shortcode and popular post view widget use advanced search sorting options, these will need to be valideated through the functions
geodir_widget_listings_get_order()
gdsc_validate_sort_choice()

https://wpgeodirectory.com/support/topic/sort-listings-by-price-questions/#post-371167

**Comment by kprajapatii** [comment]
Fixed
https://github.com/GeoDirectory/geodirectory/pull/383/commits/e8e11880ad5775ce1c19cdf46f49d8060ebfb972
