### ISSUE TITLE
Some strings cannot be translated

### ISSUE THREAD

**Issue by srdjan-jcc** [GeoDirectory/geodirectory#449]
Hello,
some texts coming from GeoDirectory cannot be translated
because are not wrapped in gettext calls.

https://github.com/GeoDirectory/geodirectory/blob/0cf57c43ef53784000ff4c7826dffb94bd8f9058/geodirectory_template_actions.php#L2472

https://github.com/GeoDirectory/geodirectory/blob/0cf57c43ef53784000ff4c7826dffb94bd8f9058/geodirectory_template_actions.php#L2545

Can you please consider using gettext calls instead of constants for texts used in these places?

Something like:
`<input type="submit" value="<?php _e('Review Your Listing', 'geodirectory'); ?>"`

**Comment by Stiofan** [comment]
Hello,

These strings are called PHP Constants, they are defined in other parts of the script and are fully translatable: https://github.com/GeoDirectory/geodirectory/blob/048c843ece7d61d669b415aeae40e6093b44460c/language.php#L72

Thanks,

Stiofan
