### ISSUE TITLE
Best of widget not responsive

### ISSUE THREAD

**Issue by NomadDevs** [GeoDirectory/geodirectory#7]
the best of widget is not responsive, also when loading new lstings can u use the same fade in and same loading icon used in the popular categories widget, u can see here: http://ppl.directory/

**Comment by mistergiri** [comment]
https://github.com/GeoDirectory/geodirectory/pull/9

**Comment by NomadDevs** [comment]
spinner not right, not centerd int he places box and not showing on mobile.
It might best to load the dropdown select and hide it and then change to that on mobile?

**Comment by mistergiri** [comment]
ok,i'll check that tomorrow
